print('Hello world!'.startswith('Hello'))
print('Hello world!'.endswith('world!'))
print('abc123'.startswith('12'))
print('abc123'.endswith('12'))
print('Helo world!'.startswith('Hello world!'))
print('Hello wordl!'.endswith('Hello world!'))

print('Hello'.rjust(10))
print('Hello'.rjust(20))
print('Hello world'.rjust(20))
print('Hello'.ljust(10))
print('Hello'.rjust(20,'*'))
print('Hello'.rjust(20,'-'))
print('Hello'.center(20))
print('Hello'.center(20,'='))